server:
  port: 9090

#前端的默认端口
#const defaultDomain = "localhost:9090";

database:
  driver-class-name: com.mysql.cj.jdbc.Driver
  engine: MySQL
  url: jdbc:mysql://127.0.0.1:3306/landlords?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
  username: root
  password: 123456
#database:
#  engine: SQLite
#  url: jdbc:sqlite:db/landlords.sqlite3
#  username:
#  password:

landlords:
  frontend-host: localhost:9000
  jwt-secret: 298b8610-6835-4d12-b8ae-efba3dbcccad

logging:
  level:
    site.pushy.landlords.dao: debug
